from dotenv import load_dotenv
import os

load_dotenv()

# Variáveis Vibra TRR
var_vbr = {}
var_vbr['link'] = os.getenv('LINK_VBR')
var_vbr['login'] = os.getenv('LOGIN_VBR')
var_vbr['senha'] = os.getenv('SENHA_VBR')
var_vbr['xpath_input_login'] = os.getenv('XPATH_INPUT_LOGIN_VBR')
var_vbr['xpath_input_senha'] = os.getenv('XPATH_INPUT_SENHA_VBR')
var_vbr['xpath_button_entrar'] = os.getenv('XPATH_BUTTON_ENTRAR_VBR')
var_vbr['link_pedidos'] = os.getenv('LINK_PEDIDOS_VBR')
var_vbr['id_input_qtdlitros_s10'] = os.getenv('ID_INPUT_QTDLITROS_S10_VBR')
var_vbr['id_input_qtdlitros_s500'] = os.getenv('ID_INPUT_QTDLITROS_S500_VBR')
var_vbr['xpath_button_atualizar'] = os.getenv('XPATH_BUTTON_ATUALIZAR_VBR')
var_vbr['id_select_prazo_s10'] = os.getenv('ID_SELECT_PRAZO_S10_VBR')
var_vbr['id_select_prazos500'] = os.getenv('ID_SELECT_PRAZO_S500_VBR')
var_vbr['prazo'] = os.getenv('PRAZO_VBR')
var_vbr['xpath_preco_s10'] = os.getenv('XPATH_PRECO_S10_VBR')
var_vbr['xpath_preco_s500'] = os.getenv('XPATH_PRECO_S500_VBR')
var_vbr['id_select_modo_s10'] = os.getenv('ID_SELECT_MODO_S10_VBR')
var_vbr['id_select_modo_s500'] = os.getenv('ID_SELECT_MODO_S500_VBR')
var_vbr['modo'] = os.getenv('MODO_VBR')

# Variáveis Vibra Janjão
var_vbr_janjao = {}
var_vbr_janjao['link'] = os.getenv('LINK_VBR')
var_vbr_janjao['login'] = os.getenv('LOGIN_VBR_JANJAO')
var_vbr_janjao['senha'] = os.getenv('SENHA_VBR_JANJAO')
var_vbr_janjao['xpath_input_login'] = os.getenv('XPATH_INPUT_LOGIN_VBR')
var_vbr_janjao['xpath_input_senha'] = os.getenv('XPATH_INPUT_SENHA_VBR')
var_vbr_janjao['xpath_button_entrar'] = os.getenv('XPATH_BUTTON_ENTRAR_VBR')
var_vbr_janjao['link_pedidos'] = os.getenv('LINK_PEDIDOS_VBR')
var_vbr_janjao['xpath_preco_etanol'] = os.getenv('XPATH_PRECO_ETANOL_VBRJJ')
var_vbr_janjao['xpath_preco_gasolina'] = os.getenv('XPATH_PRECO_GASOLINA_VBRJJ')
var_vbr_janjao['xpath_preco_s10'] = os.getenv('XPATH_PRECO_S10_VBRJJ')
var_vbr_janjao['xpath_preco_s500'] = os.getenv('XPATH_PRECO_S500_VBRJJ')
var_vbr_janjao['xpath_button_atualizar'] = os.getenv('XPATH_BUTTON_ATUALIZAR_VBR')
var_vbr_janjao['id_select_modo_etanol'] = os.getenv('ID_SELECT_MODO_ETANOL_VBRJJ')
var_vbr_janjao['id_select_modo_gasolina'] = os.getenv('ID_SELECT_MODO_GASOLINA_VBRJJ')
var_vbr_janjao['id_select_modo_s10'] = os.getenv('ID_SELECT_MODO_S10_VBRJJ')
var_vbr_janjao['id_select_modo_s500'] = os.getenv('ID_SELECT_MODO_S500_VBRJJ')
var_vbr_janjao['modo'] = os.getenv('MODO_VBR')

# Variáveis Raízen
var_rzn = {}
var_rzn['link'] = os.getenv('LINK_RZN')
var_rzn['login'] = os.getenv('LOGIN_RZN')
var_rzn['senha'] = os.getenv('SENHA_RZN')
var_rzn['xpath_input_login'] = os.getenv('XPATH_INPUT_LOGIN_RZN')
var_rzn['xpath_input_senha'] = os.getenv('XPATH_INPUT_SENHA_RZN')
var_rzn['xpath_button_entrar'] = os.getenv('XPATH_BUTTON_ENTRAR_RZN')
var_rzn['link_precos'] = os.getenv('LINK_PRECOS_RZN')
var_rzn['xpath_preco_fob_s10'] = os.getenv('XPATH_PRECO_FOB_S10_RZN')
var_rzn['xpath_preco_fob_s500'] = os.getenv('XPATH_PRECO_FOB_S500_RZN')
var_rzn['xpath_preco_cif_s10'] = os.getenv('XPATH_PRECO_CIF_S10_RZN')
var_rzn['xpath_preco_cif_s500'] = os.getenv('XPATH_PRECO_CIF_S500_RZN')

# Variáveis Ipiranga
var_ipr = {}
var_ipr['link'] = os.getenv('LINK_IPR')
var_ipr['link_pedidos'] = os.getenv('LINK_PEDIDOS_IPR')
var_ipr['xpath_input_login'] = os.getenv('XPATH_INPUT_LOGIN_IPR')
var_ipr['xpath_input_senha'] = os.getenv('XPATH_INPUT_SENHA_IPR')
var_ipr['login'] = os.getenv('LOGIN_IPR')
var_ipr['senha'] = os.getenv('SENHA_IPR')
var_ipr['xpath_button_entrar'] = os.getenv('XPATH_BUTTON_ENTRAR_IPR')
var_ipr['xpath_button_cookies'] = os.getenv('XPATH_BUTTON_COOKIES_IPR')
var_ipr['xpath_button_pedidos'] = os.getenv('XPATH_BUTTON_PEDIDOS_IPR')
var_ipr['xpath_select_base'] = os.getenv('XPATH_SELECT_BASE_IPR')
var_ipr['base'] = os.getenv('BASE_IPR')
var_ipr['xpath_iframe'] = os.getenv('XPATH_IFRAME')
var_ipr['xpath_button_razao_social'] = os.getenv('XPATH_BUTTON_RAZAOSOCIAL_IPR')
var_ipr['xpath_button_ipr2'] = os.getenv('XPATH_BUTTON_IPR2')
var_ipr['id_preco_cif_s10'] = os.getenv('ID_PRECO_CIF_S10_IPR_TRR')
var_ipr['id_preco_fob_s10'] = os.getenv('ID_PRECO_FOB_S10_IPR_TRR')
var_ipr['id_preco_cif_s500'] = os.getenv('ID_PRECO_CIF_S500_IPR_TRR')
var_ipr['id_preco_fob_s500'] = os.getenv('ID_PRECO_FOB_S500_IPR_TRR')

# Variáveis Ipiranga Postos
var_ipr_postos = {}
var_ipr_postos['link'] = os.getenv('LINK_IPR')
var_ipr_postos['login'] = os.getenv('LOGIN_IPR_POSTOS')
var_ipr_postos['senha'] = os.getenv('SENHA_IPR_POSTOS')
var_ipr_postos['xpath_input_login'] = os.getenv('XPATH_INPUT_LOGIN_IPR')
var_ipr_postos['xpath_input_senha'] = os.getenv('XPATH_INPUT_SENHA_IPR')
var_ipr_postos['xpath_button_entrar'] = os.getenv('XPATH_BUTTON_ENTRAR_IPR')
var_ipr_postos['xpath_button_cookies'] = os.getenv('XPATH_BUTTON_COOKIES_IPR')
var_ipr_postos['link_pedidos'] = os.getenv('LINK_PEDIDOS_IPR')
var_ipr_postos['xpath_button_razaosocial'] = os.getenv('XPATH_BUTTON_RAZAOSOCIAL_IPR')
var_ipr_postos['xpath_iframe'] = os.getenv('XPATH_IFRAME')
var_ipr_postos['id_preco_cif_etanol'] = os.getenv('ID_PRECO_CIF_ETANOL_IPR')
var_ipr_postos['id_preco_fob_etanol'] = os.getenv('ID_PRECO_FOB_ETANOL_IPR')
var_ipr_postos['id_preco_cif_gasolina'] = os.getenv('ID_PRECO_CIF_GASOLINA_IPR')
var_ipr_postos['id_preco_fob_gasolina'] = os.getenv('ID_PRECO_FOB_GASOLINA_IPR')
var_ipr_postos['id_preco_cif_gasolinaadt'] = os.getenv('ID_PRECO_CIF_GASOLINAADT_IPR')
var_ipr_postos['id_preco_fob_gasolinaadt'] = os.getenv('ID_PRECO_FOB_GASOLINAADT_IPR')
var_ipr_postos['id_preco_cif_s10'] = os.getenv('ID_PRECO_CIF_S10_IPR')
var_ipr_postos['id_preco_fob_s10'] = os.getenv('ID_PRECO_FOB_S10_IPR')
var_ipr_postos['id_preco_cif_s500'] = os.getenv('ID_PRECO_CIF_S500_IPR')
var_ipr_postos['id_preco_fob_s500'] = os.getenv('ID_PRECO_FOB_S500_IPR')
var_ipr_postos['xpath_button_distrito'] = os.getenv('XPATH_BUTTON_DISTRITO_IPR')
var_ipr_postos['xpath_button_itirapua'] = os.getenv('XPATH_BUTTON_ITIRAPUA_IPR')
var_ipr_postos['xpath_button_ppp'] = os.getenv('XPATH_BUTTON_PPP_IPR')
var_ipr_postos['xpath_button_pitstop'] = os.getenv('XPATH_BUTTON_PITSTOP_IPR')
